name: CI
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # CHANGE_ME - implement automation test for the actual action
      - name: invoke action
        uses: ./
        with:
          input1: foo
          input2: bar

      - name: Verify the result
        run: |
          source assert.sh
          assert_eq "foo" "$DUMMY_INPUT1"
          assert_eq "bar" "$DUMMY_INPUT2"
